### ISSUE TITLE
btf_translator don't work with kernel 6.17.4

### ISSUE THREAD

**Issue by patryk4815** [tw4452852/zbpf#19]
btf_translator don't work with kernel 6.17.4

```console
[root@853b6a67226d /]# ARCH=$(uname -m) && \
    curl -fsSL "https://ziglang.org/builds/zig-${ARCH}-linux-0.16.0-dev.3013+abd131e33.tar.xz" \
    | tar -xJ -C /opt && \
    ln -s /opt/zig-*/zig /usr/local/bin/zig
[root@853b6a67226d /]# git clone https://github.com/tw4452852/zbpf /zbpf
Cloning into '/zbpf'...
remote: Enumerating objects: 1855, done.
remote: Counting objects: 100% (433/433), done.
remote: Compressing objects: 100% (143/143), done.
remote: Total 1855 (delta 305), reused 376 (delta 278), pack-reused 1422 (from 3)
Receiving objects: 100% (1855/1855), 5.01 MiB | 15.00 MiB/s, done.
Resolving deltas: 100% (1045/1045), done.
[root@853b6a67226d /]# cd /zbpf && zig build zbpf -Dbpf=samples/hash.zig
zbpf
└─ install zbpf
   └─ compile exe zbpf Debug native
      └─ run exe btf_sanitizer (hash_sanitized.o)
         └─ compile obj hash ReleaseFast bpfel-freestanding 940 errors
.zig-cache/o/c4c6491206b3c75c32de7da4b33d4535/vmlinux.zig:57:28: error: use of undeclared identifier 'type_tag_25'
pub const ptr_to_rcu = ?[*]type_tag_25;
                           ^~~~~~~~~~~
.zig-cache/o/c4c6491206b3c75c32de7da4b33d4535/vmlinux.zig:300:31: error: use of undeclared identifier 'type_tag_106'
pub const ptr_to_percpu = ?[*]type_tag_106;
                              ^~~~~~~~~~~~

.... manymany more 
```

**Comment by renatus-cartesius** [comment]
+1
```
...
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:239417:35: error: use of undeclared identifier 'type_tag_53813'
pub const ptr_to_rcu__53814 = ?[*]type_tag_53813;
                                  ^~~~~~~~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:239963:38: error: use of undeclared identifier 'type_tag_53909'
pub const ptr_to_percpu__53910 = ?[*]type_tag_53909;
                                     ^~~~~~~~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:249333:44: error: use of undeclared identifier 'type_tag_76998'
pub const @"ptr_to_address_space(1)" = ?[*]type_tag_76998;
                                           ^~~~~~~~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:333463:95: error: use of undeclared identifier 'long_int'
pub const msgrcv = fn (msqid: Kernel.int, msgp: *Kernel.msgbuf, msgsz: Kernel.size_t, msgtyp: long_int, msgflg: Kernel.int) c_long;
                                                                                              ^~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:333469:54: error: use of undeclared identifier 'long_int'
pub const truncate = fn (path: *Kernel.char, length: long_int) c_long;
                                                     ^~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:333494:33: error: use of undeclared identifier 'long_int'
pub const ptrace = fn (request: long_int, pid: long_int, addr: c_ulong, data: c_ulong) c_long;
                                ^~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:333590:68: error: use of undeclared identifier 'long_int'
pub const io_getevents = fn (ctx_id: Kernel.aio_context_t, min_nr: long_int, nr: long_int, events: *Kernel.io_event, timeout: *Kernel.__kernel_timespec) c_long;
                                                                   ^~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:333591:61: error: use of undeclared identifier 'long_int'
pub const io_submit = fn (ctx_id: Kernel.aio_context_t, nr: long_int, iocbpp: **Kernel.iocb) c_long;
                                                            ^~~~~~~~
.zig-cache/o/04285b3fd6489f62e46596c5d6eaa204/vmlinux.zig:333712:69: error: use of undeclared identifier 'long_int'
pub const io_pgetevents = fn (ctx_id: Kernel.aio_context_t, min_nr: long_int, nr: long_int, events: *Kernel.io_event, timeout: *Kernel.__kernel_timespec, usig: *Kernel.__aio_sigset) c_long;
                                                                    ^~~~~~~~
...
```

**Comment by tw4452852** [comment]
This issue should be fixed on the tip (0fc5bb890194980611398d0d511021b3d3a46b18).
However, zbpf can't accomodate to the Zig 0.16 for now, so I switch back to 0.15.2 temporarily, sorry for inconvenience.
